add firewall mode to sdwdate log
https://phabricator.whonix.org/T551

diff --git a/usr/bin/whonix_firewall b/usr/bin/whonix_firewall
--- a/usr/bin/whonix_firewall
+++ b/usr/bin/whonix_firewall
@@ -14,10 +14,15 @@
 set -e
 
 error_handler() {
-  echo "##################################################"
-  echo "Whonix firewall script failed!"
-  echo "##################################################"
-  exit 1
+   echo "##################################################"
+   echo "Whonix firewall script failed!"
+   echo "##################################################"
+
+   echo "$0 ##################################################" >> /var/log/sdwdate.log || true
+   echo "$0 Whonix firewall script failed!" >> /var/log/sdwdate.log || true
+   echo "$0 ##################################################" >> /var/log/sdwdate.log || true
+
+   exit 1
 }
 
 trap "error_handler" ERR
@@ -27,6 +32,11 @@ init() {
 
    set -o pipefail
    set -o errtrace
+
+   ## In case sdwdate is not installed.
+   ## Defensive measure to not mess up file permissions.
+   mkdir --parents /var/run/sdwdate
+   chown --recursive sdwdate:sdwdate /var/run/sdwdate
 }
 
 source_config_folder() {
@@ -609,18 +619,23 @@ status_files() {
    touch /var/run/whonix_firewall/first_run_current_boot.status
 }
 
+echo_and_sdwdate_log() {
+   echo "$@"
+   echo "$0 $@" >> /var/log/sdwdate.log || true
+}
+
 firewall_mode_detection() {
    if [ ! "$firewall_mode" = "" ]; then
-      echo "OK: Skipping firewall mode detection since already set to '$firewall_mode'."
+      echo_and_sdwdate_log "OK: Skipping firewall mode detection since already set to '$firewall_mode'."
       if [ "$firewall_mode" = "timesync-fail-closed" ]; then
-         echo "OK: (Only local Tor control port connections and torified sdwdate allowed.)"
+         echo_and_sdwdate_log "OK: (Only local Tor control port connections and torified sdwdate allowed.)"
          return 0
       elif [ "$firewall_mode" = "full" ]; then
-         echo "OK: Skipping firewall mode detection since already set to '$firewall_mode'."
-         echo "OK: (Full torified network access allowed.)"
+         echo_and_sdwdate_log "OK: Skipping firewall mode detection since already set to '$firewall_mode'."
+         echo_and_sdwdate_log "OK: (Full torified network access allowed.)"
          return 0
       else
-         echo "ERROR: firewall_mode must be set to either 'full' or 'timesync-fail-closed'."
+         echo_and_sdwdate_log "ERROR: firewall_mode must be set to either 'full' or 'timesync-fail-closed'."
          error_handler
       fi
    fi
@@ -628,15 +643,15 @@ firewall_mode_detection() {
    ## Run Whonix firewall in full mode if sdwdate already succeeded.
    if [ -e /var/run/sdwdate/first_success ]; then
       firewall_mode=full
-      echo "OK: (/var/run/sdwdate/first_success exists.)"
+      echo_and_sdwdate_log "OK: (/var/run/sdwdate/first_success exists.)"
    elif [ -e /var/run/sdwdate/success ]; then
       firewall_mode=full
-      echo "OK: (/var/run/sdwdate/success exists.)"
+      echo_and_sdwdate_log "OK: (/var/run/sdwdate/success exists.)"
    ## /var/run/whonix_firewall/first_run_current_boot.status already exists,
    ## therefore have Whonxi firewall run in full mode.
    elif [ -e /var/run/whonix_firewall/first_run_current_boot.status ]; then
       firewall_mode=full
-      echo "OK: (/var/run/whonix_firewall/first_run_current_boot.status exists.)"
+      echo_and_sdwdate_log "OK: (/var/run/whonix_firewall/first_run_current_boot.status exists.)"
    else
       ## /var/run/whonix_firewall/first_run_current_boot.status does not yet exist,
       ## therefore return 'yes, timesync-fail-closed'.
@@ -644,18 +659,18 @@ firewall_mode_detection() {
    fi
 
    if [ "$firewall_mode" = "timesync-fail-closed" ]; then
-      echo "OK: First run during current boot, therefore running in timesync-fail-closed mode."
-      echo "OK: (Only local Tor control port connections and torified sdwdate allowed.)"
+      echo_and_sdwdate_log "OK: First run during current boot, therefore running in timesync-fail-closed mode."
+      echo_and_sdwdate_log "OK: (Only local Tor control port connections and torified sdwdate allowed.)"
    else
-      echo "OK: Consecutive run during current boot, therefore running in full mode."
-      echo "OK: (Full torified network access allowed.)"
+      echo_and_sdwdate_log "OK: Consecutive run during current boot, therefore running in full mode."
+      echo_and_sdwdate_log "OK: (Full torified network access allowed.)"
    fi
 }
 
 end() {
    echo "OK: The firewall should not show any messages,"
    echo "OK: besides output beginning with prefix OK:..."
-   echo "OK: Whonix firewall loaded."
+   echo_and_sdwdate_log "OK: Whonix firewall loaded."
 
    exit 0
 }
