improve Whonix-Host detection

diff --git a/usr/bin/whonix_firewall b/usr/bin/whonix_firewall
--- a/usr/bin/whonix_firewall
+++ b/usr/bin/whonix_firewall
@@ -18,10 +18,9 @@ elif [ -f "/usr/share/anon-gw-base-files/gateway" ]; then
    /usr/bin/whonix-gateway-firewall
 elif [ -f "/usr/share/anon-ws-base-files/workstation" ]; then
    /usr/bin/whonix-workstation-firewall
+elif [ -f "/usr/share/whonix-libvirt/marker" ]; then
+   /usr/bin/whonix-host-firewall
 else
-   if /usr/share/whonix-libvirt/marker ; then
-      /usr/bin/whonix-host-firewall
-   else
-      echo "ERROR: Neither file /usr/share/anon-gw-base-files/gateway nor file /usr/share/anon-ws-base-files/workstation exists! If this is a Whonix-Gateway, package anon-gw-base-files needs to be installed. If this is a Whonix-Workstation, package anon-ws-base-files needs to be installed." >&2
+   echo "ERROR: Neither file /usr/share/anon-gw-base-files/gateway nor file /usr/share/anon-ws-base-files/workstation exists! If this is a Whonix-Gateway, package anon-gw-base-files needs to be installed. If this is a Whonix-Workstation, package anon-ws-base-files needs to be installed." >&2
    exit 1
 fi
