sanity test

diff --git a/usr/bin/whonix_firewall b/usr/bin/whonix_firewall
--- a/usr/bin/whonix_firewall
+++ b/usr/bin/whonix_firewall
@@ -40,6 +40,15 @@ for i in /etc/whonix_firewall.d/*; do
          true "skip $i"
          continue
       fi
+      bash_n_exit_code="0"
+      bash_n_output="$(bash -n "$i" 2>&1)" || { bash_n_exit_code="$?" ; true; };
+      if [ ! "$bash_n_exit_code" = "0" ]; then
+         echo "Invalid config file: $i
+bash_n_exit_code: $bash_n_exit_code
+bash_n_output:
+$bash_n_output" >&2
+         exit 1
+      fi
       source "$i"
    fi
 done
